### ISSUE TITLE
How do you actually use the resulting data?

### ISSUE THREAD

**Issue by drewid** [oNaiPs/secrets-to-env-action#260]
I've tried to figure out how to use the resulting data but have not been able to do so.
I cannot echo the data that is returned.
When I have the data I want to be able to loop through it and use it.
Any suggestions?

**Comment by getBoolean** [comment]
What does your action look like?

**Comment by oNaiPs** [comment]
@drewid not sure what you mean by resulting data. This action directly sets the OS environment variables with the same content as the github keys. Did you look at the README?
